modLoader="javafml"
loaderVersion="[36,)"
logoFile="HellasAudio.png"
license="Restricted"

[[mods]]
modId="hellasaudio"
version="2.1.0"
displayName="HellasAudio"
displayURL="https://discord.pixelmon-server.com"
credits="xSasaki_Haise"
authors="xSasaki_Haise"
description='''
Welcome to Hellas :)
'''

[[dependencies.hellasaudio]]
modId="forge"
mandatory=true
versionRange="[36,)"
ordering="NONE"
side="BOTH"

[[dependencies.hellasaudio]]
modId="minecraft"
mandatory=true
versionRange="[1.16.5,)"
ordering="NONE"
side="BOTH"

[[dependencies.hellasaudio]]
modId="hellascontrol"
mandatory=true
versionRange="[1.0.0,)"
ordering="NONE"
side="BOTH"