modLoader="javafml"
loaderVersion="[36,)"
logoFile="HellasMineralogy.png"
license="Restricted"

[[mods]]
modId="hellasmineralogy"
version="1.0.0"
displayName="HellasMineralogy"
displayURL="https://discord.pixelmon-server.com"
credits="xSasaki_Haise"
authors="xSasaki_Haise"
description='''
Welcome to Hellas :)
Explore the mineral wealth of the region.
'''

[[dependencies.hellasmineralogy]]
modId="forge"
mandatory=true
versionRange="[36,)"
ordering="NONE"
side="BOTH"

[[dependencies.hellasmineralogy]]
modId="minecraft"
mandatory=true
versionRange="[1.16.5,)"
ordering="NONE"
side="BOTH"

[[dependencies.hellasmineralogy]]
modId="hellascontrol"
mandatory=true
versionRange="[1.0.0,)"
ordering="NONE"
side="BOTH"
